name: yugomobile
description: Yugo Smart Mobility Platform

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  khalti_flutter: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # your other dependencies...

dependency_overrides:
  intl: ^0.18.0

  # State Management
  flutter_riverpod: ^2.4.9

  # UI
  gap: ^3.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4
  lottie: ^2.7.0

  # Navigation
  go_router: ^12.0.0

  # Networking
  dio: ^5.3.3
  logger: ^2.0.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # NFC/QR
  nfc_manager: ^3.2.0
  qr_code_scanner: ^1.0.1

  # Localization
  easy_localization: ^3.0.2
  # Payments
  khalti_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mocktail: ^1.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/lottie/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600